[project]
name = "gemini-key-rotator"
version = "0.1.0"
description = "Add your description here"
readme = "readme.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=23.0.0",
    "google-genai>=0.3.0",
    "json-repair>=0.25.0",
    "nest-asyncio>=1.5.0",
    "tqdm>=4.65.0",
]
